### ISSUE TITLE
Free API alternative

### ISSUE THREAD

**Issue by kcoderhtml** [Nutlope/aicommits#130]
### Feature request

The ability to use https://github.com/ayaka14732/ChatGPTAPIFree to allow for free use of the tool.

### Why?

I don't have a paid API key.

**Comment by privatenumber** [comment]
Interesting request...

I don't think it will be a good idea to point to an unofficial reverse-proxy server like (e.g. https://github.com/ayaka14732/ChatGPTAPIFree - https://freechatgpt.chat) because it can be unstable or malicious, and this tool can send sensitive/proprietary data.

There may be a way to interact with the API without a paid key using https://github.com/transitive-bullshit/chatgpt-api, but looks like it relies on an unofficial server too:

https://github.com/transitive-bullshit/chatgpt-api/blob/acfaa50875f2aca9a7fa507883b60dfdfc2faaef/src/chatgpt-unofficial-proxy-api.ts#L39

**Comment by kcoderhtml** [comment]
Okay, that makes sense, I'm currently trying to set it up for myself with the ChatGPT AI free proxy but it makes sense not to have that be the default.

**Comment by jaroslaw-weber** [comment]
any updates? ticket got closed without resolution.

**Comment by kcoderhtml** [comment]
I just ended up paying for it. You might be able to self-host a LLM and proxy the requests to OpenAI back to your own machine.
