### ISSUE TITLE
Can you provide a version that does not require Global installation?

### ISSUE THREAD

**Issue by malker97** [Nutlope/aicommits#133]
### Feature request

Guidance installed only for the current user

### Why?

I tried to use the university's development server to run Aicommits, but the student account is not in the Super User's group, and students cannot use the NPM `-g` instructions. Therefore, I think there may be many users with related problems. It is recommended that you add only instructions for ordinary users.

### Alternatives

I suggest installing the current user's base directory, and then inserting `alias aicommits="<npm install path>"` in the corresponding Command RC file to run AI Commit

**Comment by privatenumber** [comment]
The distribution published is global/local agnostic. Global/local is just how you install it.

To install the package globally within your home directory, you should follow these instructions:
https://stackoverflow.com/a/59227497/911407

Since this is an npm issue rather than an aicommits one (you'll have this problem globally installing any package), I don't think it should be addressed here.
