### ISSUE TITLE
Bug:  Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by graup** [Nutlope/aicommits#5]
Getting this error. (I have added a new API key from https://platform.openai.com/account/api-keys to my env.)

```
aicommits
▲ Welcome to AICommits!
▲ Generating your AI commit message...

/Users/graup/.nvm/versions/node/v18.13.0/lib/node_modules/aicommits/bin/aicommits.js:98
        const aiCommit = json.choices[0].text;
                                     ^

TypeError: Cannot read properties of undefined (reading '0')
    at /Users/graup/.nvm/versions/node/v18.13.0/lib/node_modules/aicommits/bin/aicommits.js:98:38
    at Generator.next (<anonymous>)
    at fulfilled (/Users/graup/.nvm/versions/node/v18.13.0/lib/node_modules/aicommits/bin/aicommits.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

**Comment by Nutlope** [comment]
Hey @graup, thanks for opening this issue! This error typically happens when you don't have the correct value for the OpenAI env variable. I recommend you do a `printenv OPENAI_API_KEY` to see what value you have it set to and verify that it matches an API key that's on your [OpenAI API dashboard](https://platform.openai.com/account/api-keys) that you linked. 

The API key should have no whitespaces and should be in the shape of `sk-xxxxxxxxxxxxxxx`. Could you verify you have the correct value for the env variable, open a brand new terminal, try it out again, then let me know if the problem is still there?

**Comment by graup** [comment]
Thanks for your reply! I tried that, same problem. If you have no idea, I'll try checking out your repo and digging into the API response.

**Comment by Nutlope** [comment]
@graup I unfortunately don't have any idea why it isn't working for you since multiple people have told me it works. But you and someone else created identical issues so it seems like there is a gap somewhere, either in the docs or code.

It's a lot to ask but if you could clone the repo and try to log the API response to find the issue, I would be very grateful!

**Comment by Nutlope** [comment]
Also, can I ask what operating system you're using @graup?

**Comment by iamshabell** [comment]
Hi, I understand that you're facing the same issue that I did before. But I was able to fix it by simply restarting my terminal. Sometimes, when the terminal has been running for a while, it can start to experience some glitches or issues with its processes. So, try restarting your terminal and see if that resolves the problem for you too.

**Comment by ivorpad** [comment]
@Nutlope The error appears to be `insufficient_quota`. I had to `console.log` the `json` response from `const json = yield response.json();` and got this:

```js
{
  json: {
    error: {
      message: 'You exceeded your current quota, please check your plan and billing details.',
      type: 'insufficient_quota',
      param: null,
      code: null
    }
  }
}
```

But you need to handle this (or any other) error(s).

**Comment by alexduros** [comment]
In my case, I had to set up a payment method in my OpenAI account, and regenerate an new API Key. It worked right after.

**Comment by privatenumber** [comment]
The latest release should log the specific error from OpenAI

**Comment by kejianlin** [comment]
OCO_OPENAI_BASE_PATH=https://api.aikey.one/v1，
api后面加上/v1

源码：
```
...
createChatCompletion: (createChatCompletionRequest, options = {}) => __awaiter(this, void 0, void 0, function* () {
          const localVarPath = `/chat/completions`;
          const localVarUrlObj = new URL(localVarPath, common_1.DUMMY_BASE_URL);
        }),
...
```
